config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  resources :users, only: [:new, :create, :index] do
    collection do
      get "login", to: "users#login"
      post "login", to: "users#authentication"
      get "logout", to: "users#logout"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true
  validates :cvv_number, format: { with: /\A\d{3}\z/ }
  validates :credit_card_number, format: { with: /\A\d{4} \d{4} \d{4} \d{4}\z/ }
  validates :password, presence: true, length: { minimum: 8 }, format: { with: /\A(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[[:^alnum:]])/x }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= session[:user_id] &&
      User.find_by(id: session[:user_id])
  end

  private
  
  def already_login
    if current_user
      redirect_to root_path, flash:{ info: "Already logged in" }
    end
  end

  def require_login
    unless current_user
      redirect_to login_users_path, flash:{ danger: "You need to login first" }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_login, only: [:new, :create, :login, :authentication]
  before_action :require_login, only: [:index, :logout]

  def index; end

  def new
    @user = User.new  
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      session[:user_id] = @user.id
      flash[:success] = "User Is Created"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end 
  end

  def login
  end

  def authentication
    @user = User.where(email: params[:email]).take
    if @user && @user.authenticate(params[:password])
      reset_session
      session[:user_id] = @user.id
      flash[:success] = "Login Successfully."
      redirect_to root_path
    else
      flash.now[:danger] = "Invalid Email Or Password."
      render :login, status: :unprocessable_entity
    end
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
    redirect_to login_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :cvv_number, :credit_card_number, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secureapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type %>">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  <div class="col-md-6">
    <%= form.text_field :name, class:"form-control", placeholder:"Full Name" %>
  </div>
  <br>
  <div class="col-md-6">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
  <br>
  <div class="row">
    <div class="col-md-1">
      <%= form.password_field :cvv_number, placeholder:"Cvv", class: "form-control" %>
      <%= @user.errors.full_messages_for(:cvv_number).first %>
    </div>
    <div class="col-md-5">
      <%= form.text_field :credit_card_number, placeholder:"Credit Card Number", class: "form-control" %>
      <%= @user.errors.full_messages_for(:credit_card_number).first %>
    </div>
  </div>
  <br>
  <div class="col-md-6">
    <%= form.password_field :password, placeholder:"Password", class:"form-control" %>
    <%= @user.errors.full_messages_for(:password).first %>
  </div>
  <br>
  <%= form.submit class:"btn btn-primary" %><br>
  <%= link_to "Already Have Account?", login_users_path %>
<% end %>

app/views/users/index.html.erb
<h1>index</h1>
<%= link_to "Logout", logout_users_path, class:"btn btn-primary" %>

app/views/users/login.html.erb
<div class="container">
  <h1>Sign In</h1>
  <%= form_with url:login_users_path do |form| %>
    <div>
      <%= form.label :email, class:"col-sm-2 col-form-label" %>
      <%= form.text_field :email, class:"form-control" %>
    </div>
    <div>
      <%= form.label :password, class:"col-sm-2 col-form-label" %>
      <%= form.password_field :password, class:"form-control" %>
    </div>
    <br>
    <div>
      <%= form.submit "Login",class:"btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to "Don't Have Account?", new_user_path %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Create User</h1>
  <%= render 'form' %>
</div>